{% set name = "soap-hla" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: master
  git_url: https://github.com/adefelicibus/soap-hla.git

build:
  number: 2

requirements:
  host:
    - perl 5.26.2
    - gcc
    - zlib
  build:
    - perl 5.26.2
    - gcc
    - zlib
  run:
    - gcc
    - perl 5.26.2
    - zlib
    - python
    - perl-pathtools
    - perl-getopt-long

test:
  commands:
    - MHC_autopipeline
    - MHC_ld2pretype_score
    - MHC_sam2snp_blast
    - MHC_snp2ld_assemble
    - MHC_typing_construct

about:
  home: https://github.com/adefelicibus/soap-hla.git
  license: BSD
  license_family: BSD
  license_file: 
  summary: A flow of sequencing data analysis pipeline to type all of the HLA genes in IMGT/HLA database using capture sequenced data or WGS data with high accuracy.
  doc_url: http://soap.genomics.org.cn/SOAP-HLA.html
  dev_url: 

extra:
  recipe-maintainers:
    - adefelicibus
