{% set name = "soap-hla" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: master
  git_url: https://github.com/adefelicibus/soap-hla.git

build:
  number: 3

requirements:
  host:
    - perl 5.26.2
    - gcc_linux-64 
    - zlib
  build:
    - perl 5.26.2
    - gcc_linux-64
    - zlib
  run:
    - gcc_linux-64
    - perl 5.26.2
    - zlib
    - python
    - perl-pathtools
    - perl-getopt-long

about:
  home: https://github.com/adefelicibus/soap-hla.git
  license: BSD
  license_family: BSD
  license_file: 
  summary: A flow of sequencing data analysis pipeline to type all of the HLA genes in IMGT/HLA database using capture sequenced data or WGS data with high accuracy.
  doc_url: http://soap.genomics.org.cn/SOAP-HLA.html
  dev_url: 

extra:
  recipe-maintainers:
    - adefelicibus
